'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DecorDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DecorDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property Products() As DbSet(Of Product)
    Public Overridable Property ProductTypes() As DbSet(Of ProductType)
    Public Overridable Property Roles() As DbSet(Of Role)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property UserRoles() As DbSet(Of UserRole)

End Class
