'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductType
    Public Property productTypeId As Integer
    Public Property productType1 As String
    Public Property productTypeImage As Byte()
    Public Property categoryId As Nullable(Of Integer)

    Public Overridable Property Category As Category
    Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)

End Class
