'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserRole
    Public Property usrroleId As Integer
    Public Property usrId As Nullable(Of Integer)
    Public Property roleId As Nullable(Of Integer)

    Public Overridable Property Role As Role
    Public Overridable Property User As User

End Class
